version: "2.4"

volumes:
  sickconfig:

services:

 sickchill:
   image: frank3427/sickchill:latest
   container_name: sickchill
   environment:
     - DOCKUID=1000
     - DOCKGID=1000
     - DOCKUPGRADE=1

   volumes:
     - 'sickconfig:/data'
     - '/etc/localtime:/etc/localtime:ro'
     - '/Tv:/tv'
     - '/Torrents:/downloads'
     - '/Downloads/rtorrent/watch/:/watch'
   ports:
     - 8081:8081
   restart: unless-stopped
